### ISSUE TITLE
Page creation issue

### ISSUE THREAD

**Issue by Puddingboy** [AnimalDesign/bolt-translate#10]
I notice that creating a page, sometimes previous content fills the page. Please note: I first prefilled the page with dummy content using the fill option.

Now after deleting a truckload of pages, previously removed content shows up on the page id's of freshly created pages. page ID1 which should be filled with the title Nieuws shows up on the page as Istam.... asdf something. The same goes for my empty body, which is now filled with this previously removed content.

Any idea what is going on? Did you do any updates I haven't used yet?
*edit: even after clearing cache and updating extenstion files, the issue remains.

To clarify: Old content shows up on the frontend, yet new content exists within the adminpanel. I believe content is not fetched or refreshed properly. I am also having errors after attempting to bulk remove pages. If I do. I get sent to an errorpage. After returning the the adminpanel only the first selected page gets removed.

**Comment by SahAssar** [comment]
Could you update to 1.1.2 (which I just tagged, so it might take an hour for it to appear in bolt's extensions) and see if the issue persists?

**Comment by Puddingboy** [comment]
I just updated, but I'm still having an issue. My homepage content which is tied to page Id16 right now, but the on the user side we still see page content of a Diensten page that isn't supposed to exist anymore since I personally deleted that page.

**Comment by SahAssar** [comment]
@Puddingboy Yeah, you can just delete all the rows in the bolt_translation table... But first could you check in there and see if the content looks correct? I'm sorta having a hard time debugging this...

**Comment by Puddingboy** [comment]
Can you give me a list of steps i can go through to help you out in figuring out what's going on?

**Comment by SahAssar** [comment]
Basically the translation table has 5 columns, locale, field, content_type_id, content_type and value.

The first four are set as the primary key, so just find the row where value contains the text for your homepage, and see if it is set to the correct content_type_id and content_type.

**Comment by Puddingboy** [comment]
I am familiar with commandprompt, sublime text3 and phpmyadmin. What programs are generally used to edit these tables? I am working with filezilla by ftp to edit these files. I'm open to a new approach if needed.

**Comment by SahAssar** [comment]
If you are using MySQL HeidiSQL should work fine, if you are on SQLite you can use http://sqlitebrowser.org/.

**Comment by Puddingboy** [comment]
After doing a clean install I already get an issue between the install steps 3-5. claiming locale is not a valid type for locale:
```
pages:
    name: Pages
    slug: pages
    singular_name: Page
    singular_slug: page
    class: \Bolt\Extension\Animal\Translate\Content\LocalizedContent
    fields:
        locale:
            type: locale
            group: content
```

Do I need to change type to something else or did I forget something?

**Comment by SahAssar** [comment]
Hmm, as long as "locales" is set in your main configuration it should load the field... is locales set in your config.yml? if so, what is it set to?

**Comment by Puddingboy** [comment]
I just saw that my changes to locales were not omitted after hitting save. After doing so I noticed you are using en to refer to the locale in the routing but for a more clear example I would use en_EN. At least that notation was required for me.

On a sidenote I got a message from our IT guy who told me your code was written for a 5.4+, but for the server we'll be placing our bolt setup on we'll be running 5.3.3 (it has some other stuff running too, so we can't just go and upgrade the server as we please)

These are errors we encounter while running bolt with translate extension

```
Error: syntax error, unexpected '['
File: extensions/vendor/animal/translate/Extension.php
Line: 108

$routeParams['_locale'] = reset($locales)['slug'];
 $locales = reset ($locales);
                    $routeParams['_locale'] = $locales['slug'];
```

```
Error: syntax error, unexpected '['
File: extensions/vendor/animal/translate/Extension.php
Line: 227

$value->vars['label'] = $this->app['twig']->render('/twig/trans.twig', ['value' => $value->vars['label'] ]);
$value->vars['label'] = $this->app['twig']->render('/twig/trans.twig', $this->app['value'] = $value->vars['label']);
```

```
Error: syntax error, unexpected '['
File: extensions/vendor/animal/translate/Extension.php
Line: 230

$value->vars['attr']['placeholder'] = $this->app['twig']->render('/twig/trans.twig', ['value' => $value->vars['attr']['placeholder'] ]);
$value->vars['attr']['placeholder'] = $this->app['twig']->render('/twig/trans.twig', $this->app['value'] = $value->vars['attr']['placeholder']);
```

```
Error: syntax error, unexpected '['
File: extensions/vendor/animal/translate/src/Frontend/LocalizedFrontend.php
Line: 103

return $app->redirect(reset($app['config']->get('general/locales'))['slug']);
$value = $app['config']->get('general/locales');
   $redirect = reset ($value['slug']);
   return $app->redirect($redirect);
```

```
Bolt – Critical error.
Class InvalidArgumentException
Bericht: Cannot redirect to an empty URL.
Code 0
```

So it seems default language redirection fails

**Comment by SahAssar** [comment]
The extension checks for the "en" way to define a language in the _locale parameter and gets the respective "en_GB" langaugecode when fetching from the database, so that shouldn't be an issue AFAIK.

The issue makes a lot more sense now that I know that you are on php 5.3, I'll change the syntax in those places to be compatible with php 5.3 and release an update in an hour or so.

**Comment by Puddingboy** [comment]
I'm actually not working on php 5.3. I'm working on 5.4. Only the first paragraph was the issue I was having. Everything past that is a recent test for the other server

**Comment by SahAssar** [comment]
Ah, sorry. Do you have any errors in the js console or in bolt's system log? Did you check the DB?

**Comment by Puddingboy** [comment]
I'm not having any particular php or js errors that I can tell. Do you have to update the version number so I can download the extension with the recent changes?

**Comment by SahAssar** [comment]
Yeah, I just tagged a release, but none of those should have effected your PHP 5.4 install... Did you check the DB as we spoke about in https://github.com/AnimalDesign/bolt-translate/issues/10#issuecomment-188671744 ?

**Comment by Puddingboy** [comment]
After changing the nl_NL in routing to just nl I did not get any further errors.

**Comment by Puddingboy** [comment]
I'm getting an error after deleting a recently created page. I purposefully deleted a page to see if this error persists. 

http://puu.sh/nm4No/754405e1ed.png

I got the error after hitting the delete from the dropdown menu here on the right:
http://puu.sh/nm4Qf/33e02da910.png

I've got my assumptions previous database issues came from this issue too.

Have you got any ideas to this?

**Comment by SahAssar** [comment]
Yeah, sorry, I forgot that I snuck a fix for that into the php 5.3 update too, so just update to 0.1.3 and that should be fixed!

**Comment by Puddingboy** [comment]
should I clean my database just in case? how do I find the table I am looking for using your previously mentioned DB browser. I was hoping to find some data I could read and understand, but I'm having some troubling finding what I'm looking for.

**Comment by Puddingboy** [comment]
I found it already. I found a table for your translate plugin with 3 entries for ID2.

I just deleted those 3. Would this be enough or are you using other tables aswell?

**Comment by SahAssar** [comment]
bolt_translation is the only table used for translated fields, so that should be enough.

**Comment by Puddingboy** [comment]
I'm also not too familiar yet with bolt in general and I'm sure you can tell, but I was just wondering if it is generally possible to change page Id's in a way that I can reorder my menu and nextpage prevpage links?

**Comment by SahAssar** [comment]
Previous and next are usually decided using datepublished, but you can pass in a custom parameter if you want to sort by something else, see here: https://github.com/bolt/bolt/blob/0b93c1797693e4a679f7082e98099d168a6fb14e/src/Content.php#L1255-L1257

The order of the menu should just be the order of the items in your menu.yml, so that's unrelated to the Id's...

**Comment by Puddingboy** [comment]
I don't mean to push you, but have you got any progress in regards to splitting the search by language?

**Comment by SahAssar** [comment]
Sorry, no... I have been pushed into other projects at work, so that might be a while... I'm going to try to fix any bugs in this extension as soon as I know about them, but when it comes to functionality that will probably take a little while (a few weeks at least)...

**Comment by Puddingboy** [comment]
Do you have a temporary solution if I would just want to display the results for 1 language for now so that I at least can display a search for the main language?

**Comment by SahAssar** [comment]
IIRC search should work for the main language just like expected, it just won't work for any other language...

**Comment by SahAssar** [comment]
Just tested it, yeah, searching works for the main language, just not any other language.

**Comment by Puddingboy** [comment]
ok. I've got a question about the language tab(locales tab?). How come it is visible if I hit Save & create new page, but not when I first create a page. It's not a bother or anything, it just left me wondering.

**Comment by SahAssar** [comment]
It's because it needs an id to save translated content, and before a page is saved for the first time it doesn't have an id...

**Comment by Puddingboy** [comment]
is Save & create new page a bit fragile atm? Should I avoid it?

**Comment by Puddingboy** [comment]
Any idea why my custom localeswitcher returns empty space at the moment? I placed it within my theme and used `{{ localeswitcher('_my_localeswitcher.twig')|raw }} to fetch it. removing the `|raw` part doesn't even throw an error. I wish I could say the localeswitcher itself is empty right now, but it isn't. I've costumized the one located in your extension for now, but I don't think this is a good long term solution since a single update will throw things off again.

**Comment by SahAssar** [comment]
Is your custom localeswitcher in the root folder of your theme? If so could you post the code here?

Also, save&create new shouldn't persist the old id, but if it does then that is definitely very fragile and should not be used until I can get a patch out...

**Comment by SahAssar** [comment]
I very much appreciate your input and bug-hunting, but this issue is getting very long and unwieldy, I'd prefer if we closed this one (if the original issue is indeed fixed) and that you open a new one for each individual bug/question that is unfixed/unanswered, that way I can also refer to issues from commits and it will be easier to see which are actually fixed or not.

Would you be okay with that?

**Comment by Puddingboy** [comment]
Ofcourse

**Comment by SahAssar** [comment]
Alrightio, then I'm closing this one, if you still experience the original issue ("when creating a page, sometimes previous content fills the page"), then feel free to reopen this :)

Thanks for understanding!
