### ISSUE TITLE
[QUESTION] Page specific fields

### ISSUE THREAD

**Issue by RickvanB** [AnimalDesign/bolt-translate#107]
Hi,

Sorry for opening an issue again, but I have a question. In my current setup I have page specific fields. These are defined in my theme.yml file. It looks like the plugin doesn't do anything with it.

Does the plugin do anything with theme.yml?

**Comment by SahAssar** [comment]
Hey again @RickvanB!

To translate template specific fields set the `templateselect` field in your contenttypes.yml as translateable and then it should work. Lemme know if it doesn't work for you!

**Comment by RickvanB** [comment]
Thanks! It works now.

**Comment by RickvanB** [comment]
Question again, is it possible to translate blocks?

**Comment by SahAssar** [comment]
If you mean blocks as in the contenttype, sure it's translated just like any other contenttype. If you don't mean that I'm not sure what you mean?

**Comment by RickvanB** [comment]
@SahAssar Yes, blocks as in a contenttype.
This is the contenttype:
`blocks:
    name: Blocks
    singular_name: Block
    fields:
        title:
            type: text
            class: large
            group: "Block"
        slug:
            type: slug
            uses: [ title ]
        text-one:
            type: text
            label: Tekst 1
            group: content
            is_translateable: true
        text-two:
            type: text
            label: Tekst 2
            group: content
            is_translateable: true
        text-three:
            type: text
            label: Tekst 3
            group: content
            is_translateable: true
        text-four:
            type: text
            label: Tekst 4
            group: content
            is_translateable: true
        text-five:
            type: text
            label: Tekst 5
            group: content
            is_translateable: true
        text-six:
            type: text
            label: Tekst 6
            group: content
            is_translateable: true`

**Comment by SahAssar** [comment]
Yeah, just add the locale fields ans so on just like any other content type and it should work.
