### ISSUE TITLE
RFC: Extend the description in the extensions site

### ISSUE THREAD

**Issue by evertalbers** [AnimalDesign/bolt-translate#111]
I noticed that the bolt-translate extension cannot be found in the extensions store by searching for terms as 
- Language
- Languages
- Localisation
- Multilanguage

So I guess you catch my drift. You could even add something like "Comparable with WPML - but much better" , because some people may be looking for a WPML replacement :-) 
(and there might be comparable plugins for other CMS'es that I'm not aware of)

**Comment by SahAssar** [comment]
Added a few via 231be54204b393f6f61edafb3c7d46ccfeb59598, if you have ideas for more please let me know or PR them. I'm not really liking tagging it with the names of plugins for other CMS'es though, but that's personal and if other folks feel that it'd help I'm open to including them too.

Closing for now, feel free to comment/reopen if you come up with more keywords and don't want to PR :)
