### ISSUE TITLE
[BUG] incorrect urls in language dropdown

### ISSUE THREAD

**Issue by Lagaffe** [AnimalDesign/bolt-translate#113]
The dropdown in the administrator to switch between languages when editing a content type doesn't work anymore since the latest release. I believe it might be related to the changes for the following Bolt issue: https://github.com/bolt/bolt/issues/6514.

We are running Bolt in a subfolder on the server and are using docker containers. The url created references the name of the docker container, not the website address.

Details
-------

 - Translate Version: 4.0.5
 - Install type: Extension Repository
 - Bolt Version: 3.2.9
 - PHP version: 7.1
 - Used webserver: Apache
 - For UX/UI issues: all browsers

using docker container php:7.1-apache

Reproduction
------------

1. Open Bolt administrator
2. Create a new content type that has multilingual enabled
3. Switch language
4. url doesn't exist

**Comment by SahAssar** [comment]
Could you give me an example of one of the non-working URLs?? Cause it currently just uses the current _route and _route_params and adds the locale, see here: https://github.com/AnimalDesign/bolt-translate/blob/master/templates/fields/_locale.twig. If you could try switching that `url` call to a `path` call to see if that fixes it it'd be nice too :)

**Comment by Lagaffe** [comment]
This is an example of a non working URL:
https://website/website/bolt/editcontent/pages/2?_locale=nl

**Comment by Lagaffe** [comment]
changing the function used from 'url' to 'path' fixes the problem, there is a PR on the way
