### ISSUE TITLE
[BUG] Key "title" for array with keys "label, delabel, link, path" does not exist in "@bolt/frontend/_sub_menu_translated.twig

### ISSUE THREAD

**Issue by melcarthus** [AnimalDesign/bolt-translate#126]
With strict variables set to true this error gets thrown.

```
Twig_Error_Runtime in Template.php line 556: 
Key "title" for array with keys "label, delabel, link, path" does not exist in "@bolt/frontend/_sub_menu_translated.twig" at line 24.
```

I looked like this happend all of a sudden. I was filling pages and other content types when this error happend 'suddenly' When I clear the menu.yml everything is fine. S

Details
-------

 - Translate Version: [ 4.0.9 ]
 - Install type: [ Extension Repository ]
 - Bolt Version: [ 3.3.1 ]
 - PHP version: [ 7.0 ]
 - Used webserver: [ Apache ]

Reproduction
------------

Can't reproduce.

**Comment by SahAssar** [comment]
I think the issue is that `|default(item.title)|default('')` should have been `|default(item.title|default(''))` here: https://github.com/AnimalDesign/bolt-translate/blob/master/templates/frontend/_sub_menu_translated.twig#L24

**Comment by melcarthus** [comment]
You where right.
