### ISSUE TITLE
Label translations throws error page

### ISSUE THREAD

**Issue by Puddingboy** [AnimalDesign/bolt-translate#13]
I think this has been going on for longer and I believe it could be due to my own misconfiguration. How do I figure out what's going on?

```
Page sida/labels not found.
/vendor/silex/silex/src/Silex/Application.php
```

![](http://puu.sh/nqKhc/6415d81578.png)

![](http://puu.sh/nqKad/e303a59b9e.png)

Can you help me figure this out?

p.s: I just got word that we're having the same issue on the 5.3 server and it also seems that installing the 0.1.4 of translate throws an install error. I'll let you know when I know more. *update:

![](http://puu.sh/nqKSR/728a6ccd0c.png)

After updating the config.yml I get this:

![](http://puu.sh/nqMwI/40e0dd68c7.png)

**Comment by SahAssar** [comment]
Hmm, the first part (the routing that was bound to the contenttype 'sida') is fixed in the example routing now, the others seem to be composer/git problems... Have you changed to config to use 'http://extensions.bolt.cm/' instead of 'https://extensions.bolt.cm/' as we talked about on IRC?

**Comment by SahAssar** [comment]
Closing since fixed in IRC

**Comment by CNK001** [comment]
I have the same error, how you fixed this?

**Comment by Puddingboy** [comment]
@CNK001 what version of bolt-translate and labels are you running and what version of php? I am running bolt-translate 0.1.4 the error may origin form the latest version. If so, it may be better to open a new topic.

**Comment by SahAssar** [comment]
@CNK001 Do you have the labels extension installed? This extension currently requires it, but that will be fixed in the next version.
