### ISSUE TITLE
localeswitcher suggestion

### ISSUE THREAD

**Issue by Puddingboy** [AnimalDesign/bolt-translate#14]
```
<form action="???" id='language-preferance'>
    <select class="language-list" id="language-list">
        {% for iso, locale in locales if locale.slug == app.request.get('_locale') %}
            {{_self.localeoutput(iso, locale)}}
        {% endfor %}
        {% for iso, locale in locales if locale.slug != app.request.get('_locale') %}
            {{_self.localeoutput(iso, locale)}}
        {% endfor %}
    </select>
    <input type="submit">
</form>
{% macro localeoutput(iso, locale) %}
    {% if app.request.get('slug') != '' %}
        {% set newslug = get_slug_from_locale(record, iso) ?: record.slug %}
    {% endif %}
    <option value="{{ url(app.request.get('_route'), 
            app.request.get('_route_params')|merge({_locale: locale.slug, slug: newslug })
        )}}" {% if locale.slug == app.request.get('_locale') %}selected{% endif %}>
        {{ locale.label }}
    </option>
{% endmacro %}
```
For usabillity preferances it may be convenient to have this type of presentation. I don't want the original one to be replaced. I just would like to add this as a suggestion. The other one is just fine as is.

As for the php part of this form. I would like to leave it up to you as I'm pretty sure you have your own ideas aswell.

**Comment by madc** [comment]
Maybe we should remove the localeswitcher frontend from the extension and just add docs with information on how to implement one?

**Comment by Puddingboy** [comment]
I'm not sure about that. It may be best to leave a basic and simple example in the extension files. Within this twigfile you could then reference to your mentioned documentation so that people can indeed use their own variations.

People can use whatever output for whatever reason so I would suggest placing one basic output like this:
```
for(){
    <a href="{locale.link}">{locale.label}</a>
}
```
This way you have a very simple output that every person who can read, can also understand at some point.

Within the docs you could add a list presentation and a select box presentation as an example too. Whatever people would do with those examples would be up to them.

I still think tho that the most preferred options will be limited to anchors and selectboxes tho because of screenreaders. I am also taking into account that some people block javascript and a selectbox type would need a [php redirect](http://stackoverflow.com/questions/768431/how-to-make-a-redirect-in-php)

If people then want to add flags to the languages for example I would suggest the [javascript custom forms](https://www.psd2html.com/js-custom-forms/).

I have a personal preferance for selectboxes because to screenreaders the requested useraction is instantly communicated towards the user.

**Comment by SahAssar** [comment]
@Puddingboy How about we use the listbox role to make it accessible? Then we could include the option to have flags in it too without having to include a bunch of JS... https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_listbox_role

**Comment by Puddingboy** [comment]
That's actually a really good idea. I didn't know about the listbox role yet. Please do :)

**Comment by Puddingboy** [comment]
What about a discriptive label? is such a thing possible for those listboxes?

such as: 
`What is your favorite color? <options>`

This way it's always clear what's being asked, rather than assumed.

**Comment by SahAssar** [comment]
Yeah, we can always use https://www.w3.org/TR/wai-aria/states_and_properties#aria-label

**Comment by SahAssar** [comment]
This will probably be a part of #30 in some way, so leaving this here...

**Comment by SahAssar** [comment]
Since the localeswitcher template is so simplified now (and the locales array is available as twig global) this should be so easy to do oneself that I think having it as a option is probably superfluous. Closing, please reopen if I'm wrong!
