### ISSUE TITLE
[RFC] Make templatefields more consistend and individually managable

### ISSUE THREAD

**Issue by lenvanessen** [AnimalDesign/bolt-translate#141]
Currently, to translate a template specific field you define this in the translateselect.

Ideally, you want to be able to define this per template-specific field since this is more consistent and gives you more control.

**Comment by SahAssar** [comment]
I think that this would be really hard to do without changing how the fields are saved in bolt core... My plan was to hold out for the "successor" to template fields that is still planned for 4.0.

**Comment by lenvanessen** [comment]
Agreed
