### ISSUE TITLE
Choices not being translated

### ISSUE THREAD

**Issue by Puddingboy** [AnimalDesign/bolt-translate#15]
The choices of selectboxes are currently not being translated.

example:
http://puu.sh/nAgCU/65931864ce.png

while the label for the selectbox gets wrapped in <mark>, the options within the selectbox are not being translated.

**Comment by SahAssar** [comment]
This should now be fixed, I've done it in a way that does not really depend on this extension, but we rather ship a form_theme with it that can be used for translating boltforms.
