### ISSUE TITLE
will the translate also work properly for records?

### ISSUE THREAD

**Issue by Puddingboy** [AnimalDesign/bolt-translate#19]
I don't know how much you've actually got covered at this point.

**Comment by SahAssar** [comment]
What doesn't work for you? Cause translating fields and templatesfields in records should have been covered/fixed.

**Comment by Puddingboy** [comment]
@SahAssar oh they work just fine. I already fiddled around a little. Sorry for the late response. By the time I saw your comment I facepalmed hard that I hadn't marked this issue as solved.
