### ISSUE TITLE
Compatability with bolt 3.0

### ISSUE THREAD

**Issue by SahAssar** [AnimalDesign/bolt-translate#24]
This is outdated, see #26 for info/code

---

Well, 3.0 is out, and we've know it was coming for some time... So I'm gonna try to use this as a tracker for the issues we encounter when moving the extension to 3.0.

Besides the obvious issues of extension structure we have

* Some new nuances when it comes to mounting/overriding controllers/DI
* New js, which will have a different event structure
* And probably much more

So hopefully I can map this out in this week and get a plan for it.

**Comment by jnvsor** [comment]
Any movement on this recently?

**Comment by SahAssar** [comment]
@jnvsor I'm working on it right now, it'll pretty much be a full rewrite though.

**Comment by peterboorsma** [comment]
I'm not trying to push you here but can you say anything about a releasedate?

**Comment by SahAssar** [comment]
@peterboorsma Well, the way I'm planning to implement it (localizing the values in the PRE_HYDRATE event) has a small bug that needs fixing in bolt before I can complete/test this...

But, hopefully it won't take long after that is fixed.

**Comment by peterverraedt** [comment]
@SahAssar It is also possible to implement it by overriding the fieldtypes and localize in custom hydrate and persist-handlers, following the implementation of repeaters. For an experimental implementation of this, my [I18nTypeBase class](https://github.com/peterverraedt/bolt-translate/blob/master/src/Storage/Field/Type/I18nTypeBase.php). Note that I store translated values exactly as how repeaters work. Feel free to steal some code.

**Comment by SahAssar** [comment]
@peterverraedt Thanks, that was also my first thought when I couldn't get it working in hydration events, but IIRC that won't be very forward compatible (for 4.0). I have the basic save/persist/hydrate working now from the hydration and storage events, so now it should just be to fix up the menubuilder and then go bughunting :smile:

**Comment by peterboorsma** [comment]
I'm working on a site that needs your extension. Ik can help you with bug hunting.

**Comment by SahAssar** [comment]
@peterboorsma That'd be great! :smile: My first draft of this is in #26

Keep in mind that it's still pretty unpolished, but in my testing it's worked pretty well.

**Comment by SahAssar** [comment]
@peterboorsma Also, keep in mind that this is not compatible with latest stable due to bolt/bolt/pull/5518 not having landed yet... It will only work with 3.0-dev or master until the next 3.0 minor is released.

**Comment by peterboorsma** [comment]
Hmm.. I guess I have to wait until  bolt/bolt#5518 is fixed then. I'll ask Gawain about it.

**Comment by SahAssar** [comment]
@peterboorsma Just to be clear, it is fixed and merged into bolt, it's just that we need to tag a new release of bolt for it to be included in (that's going to be 3.10).

**Comment by SahAssar** [comment]
As noted in https://github.com/bolt/bolt/wiki/Dev-meeting-2016-07-12 we are moving forward to getting it (bolt 3.0.10) tagged, but I'd like to get a fix for repeaters in first, so that the extension is compatible with arguably the most awesome new feature of bolt 3.0. I'm going to work with rossriley on how to get it done.

Anyway, the rest of it should be pretty fine for testing, I've just disabled adding repeaters on the frontend (in legacy storage) to make sure we don't 500 a site that tries to use it. You can still save/use them on the backend though.

**Comment by peterboorsma** [comment]
I started using it. First error detected. :) See https://github.com/AnimalDesign/bolt-translate/issues/27

**Comment by SahAssar** [comment]
Closing as this is merged in... Will tag a release as soon as the next minor of bolt is tagged as that is required to make the repeaters work.
