### ISSUE TITLE
Preview and Live edit not working

### ISSUE THREAD

**Issue by frozenshadow** [AnimalDesign/bolt-translate#25]
First of all thank you for this great extension!
The whole thing is working nicely with bolt, except for the preview and live edit functionality.

I’m currently running Bolt 2.20 along with the latest version of this extension. And followed the installation manual from the readme.md (including the routing setup).

I did some small testing with the routing configuration. And found that after removing the "preview" section, live edit works but NOT the preview functionality.

**Exceptions:**
_Live edit with default “preview” routing:_
No exceptions

_Page preview with default “preview” routing:_
`No route found for "POST /nl_NL/preview/page" (from http://domain.dev/bolt/editcontent/pages/2")`

_Live edit with extension “preview” routing:_
`No route found for "POST /preview/page" (from "http://domain.dev/bolt/editcontent/pages/2")`

_Page preview with extension “preview” routing:_
No exception but undefined Page

I have no experience in developing extensions for Bolt.
So if any additional information is required, please let me know :)

**Comment by SahAssar** [comment]
I don't think that I can get live-edit working, but preview should be possible. The hard part would be to make sure that the rest of the page (menu, other content pulled in and so on) is in the locale selected in the editcontent page... I personally have never really used the live-edit or preview functionality much, are these something that you use much in bolt?

**Comment by frozenshadow** [comment]
I see, that’s a shame. I actually picked Bolt because of the live edit feature.
Is there anything I can do to make it work, maybe a workaround…?

**Comment by SahAssar** [comment]
Hmm, It seems like live-edit and preview has the same problem, which should be fixable. Basically we need to set the bolt locale around here: https://github.com/bolt/bolt/blob/release/2.2/src/Controllers/Frontend.php#L172 to make sure that the correct content is fetched and then make sure that we inject a hidden input element into the rendered live-edit doc that contains the locale...

So, it seems possible and I'll hopefully try it out tomorrow, but it probably won't be that high on my list of priorities compared to `require_slugs` or other features listed in #16

**Comment by frozenshadow** [comment]
Good to hear it’s fixable!
Looking forward for the fix (no pressure off course ;)

**Comment by KeizerDev** [comment]
Any news on this?

**Comment by SahAssar** [comment]
@KeizerDev Sorry, no. I'm working on 3.0 compatibility now and can hopefully get this working in that version and then perhaps backport it.

**Comment by SahAssar** [comment]
This is fixed in #26, but that is going to be 3.0 only, and the 2.2 and 3.0 versions of the extensions won't be compatible. After I get the 3.0 version out the door I can look at getting it on 2.2 if there is still demand.

**Comment by SahAssar** [comment]
Fixed in #26 which will soon be released for 3.0, so I'm closing... Please reopen if there is demand for this in 2.2.
