### ISSUE TITLE
Error adding 'locale' to DB (dev-master (e8f834))

### ISSUE THREAD

**Issue by peterboorsma** [AnimalDesign/bolt-translate#27]
Version: dev-master (e8f834)
Bolt version: 3.0.9. pl 1

I know it's a work in progress. But  maybe it's useful.
When adding 'locale' to the contenttype.yml fields the following error occurs after trying to update the database:

"Er is een fout opgetreden tijdens het bijwerken van de 'bolt_paginas'. De fout is An exception occurred while executing 'ALTER TABLE bolt_paginas ADD locale LONGTEXT DEFAULT '[]' NOT NULL COMMENT '(DC2Type:json_array)'': SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'locale' can't have a default value"

**Comment by madc** [comment]
Why is locale a `LONGTEXT`? Shouldn't `varchar(5)` be enought?

**Comment by SahAssar** [comment]
@peterboorsma Try now, I just pushed a fix. You're on mysql, right?

@madc Seems like it was leftover from when I was planning to use that column for the actual storage of the localized data, should be fixed now.

**Comment by peterboorsma** [comment]
Yes, MySQL.
The updater can't find a new version (current dev-master (e8f834). @bobdenotter and I tried to download it (witth the Bolt updater and command line also) but keep getting the e8f834 release.

**Comment by SahAssar** [comment]
@peterboorsma Yeah, it seems like the update button on the extension store only checks for tagged releases, not updates to dev-master... If you have CLI access to the server you can go to the directory and `git pull` to get the changes, or you can manually copy/change the changed files or you will need to wait until it get's updated in the extension store via the cronjob (which I think is nightly) and then hit update in the bolt updater.

Sorry for the inconvenience!

**Comment by peterboorsma** [comment]
No worries. It's nice to test stuff.

**Comment by SahAssar** [comment]
This seems to have been fixed in the latest 3 commits, so I'm closing,
