### ISSUE TITLE
[RFC] Simple language alternator

### ISSUE THREAD

**Issue by zomars** [AnimalDesign/bolt-translate#30]
Most of the multilingual websites I made use only 2 languages, so it's kinda overkill to present a whole dropdown menu just to switch between the two. It would be nice to have a simple link that changes depending on the current language. 

Here's my approach for `_localeswitcher.twig`:

```twig
{% for iso, locale in locales %}
    {% if app.request.get('slug') and app.request.get('_route') == 'contentlink' or app.request.get('_route') == 'pagebinding' %}
        {% set newslug = get_slug_from_locale(record, locale.slug) ?: record.slug %}
    {% else %}
        {% set newslug = app.request.get('slug') %}
    {% endif %}
    {% if locale.slug != app.request.get('_locale') %}
        <a title="{{ locale.label }}" href="{{ url(
             app.request.get('_route'),
             app.request.get('_route_params')|merge({_locale: locale.slug, slug: newslug })
             )}}">
             {{ locale.label }}
        </a>
    {% endif %}
{% endfor %}
```

**Comment by SahAssar** [comment]
@zomars: Would this be for the backend one, the frontend one or both?

**Comment by zomars** [comment]
My solution is for the frontend only, but maybe it could be implementing according to the number of the configured languages. Mine's just a quick fix.

**Comment by madc** [comment]
First, thanks for sharing your snippet. The way, I see it, the `_localeswitcher.twig`, that is included with the extension, is just demonstrating how to implement such functionality. The template of the twif function can easily be overwritten. Also, the `ul` from the default template can be styled with CSS, so will look exactly like yours.

**Comment by SahAssar** [comment]
In addition to what @madc said it is also planned to have proper language codes (as rel="alternate" and hreflang="lang-here") for each link in both a the localeswitcher and to add them to `<head>` (automatically that is), IIRC it helps search engines and accessibility to have a link that is "active"/"current" when doing that. adding `.localeswitcher .active { display: none;}` should remove that element from display while allowing you style the rest as needed, or if you want to remove it completely using a custom template should do the trick.


If I'm wrong on the accessibility front (requiring a "current" link) I think we could probably remove it though.

**Comment by madc** [comment]
One thing, that didn't leave my head since we talked about this other issue:

It would make the localeswitcher way simpler, if we would move all this url business into the php code of the twig function and just inject a clean array of objects into the template.

So from the current template we should be able to have something like:

```
<ul class="localeswitcher {{ extraclasses }}">
    {% for iso, locale in locales %}
        <li {% if locale.active %}class="active"{% endif %}>
            <a title="{{ locale.label }}" href="{{ locale.url }}">
                {{ locale.label }}
            </a>
    {% endfor %}
</ul>
```

The object could look something like this:

```
[
   en_GB: {
       active: true,
       label: English,
       url: http://whatever/en
   },
   de_AT: {
       label: German,
       url: http://whatever/de
   },
   [...]
]

**Comment by SahAssar** [comment]
@madc Yep, that's the plan... That part of the code is basically copy-pasted verbatim from the 2.2 version, so it hasn't gotten as much love as the rest. I also planned to make it available as a global in twig so that one could just loop and output it wherever without having to make a specific template for that part...

**Comment by madc** [comment]
That a good idea. I'd have a look at it, if you don't mid..

**Comment by SahAssar** [comment]
Sounds great! Then we could get rid of the ugly getSlugFromLocale function too, which hasn't seen any work for a while either.
