### ISSUE TITLE
Github webhook for extensions.bolt.cm

### ISSUE THREAD

**Issue by SahAssar** [AnimalDesign/bolt-translate#34]
@madc Could you perhaps add the github webhook for this repo? The hook to add is `https://extensions.bolt.cm/hook?token=7b894fc540811b2aa56da22953354fcc `.

I know this is a bit odd since I can't add it since it's in your github organization but the submission to extensions.bolt.cm is in my user, but we'll make it work :)

**Comment by madc** [comment]
We will.. Hope, that I will find more time to contribute again in the future.

I added the webhook and it ran successfully. Closing this issue, but feel free to re-open, if something's wrong.
