### ISSUE TITLE
[BUG] Default {{ localeswitcher() }} not working properly on subfolders

### ISSUE THREAD

**Issue by madc** [AnimalDesign/bolt-translate#36]
My local dev-environment normal is set up like `http://client.dev/<name-of-client>`. Just throwing `{{ localeswitcher() }}` into the template results in links without `<name-of-client>` (i.e. http://client.dev/en)

Details
-------

 - Translate Version: master
 - Install type: Extension Repository
 - Bolt Version: master
 - PHP version: 7.0
 - Used webserver: Apache 2.4

**Comment by SahAssar** [comment]
Hmm, I've never run bolt in subfolders, did this work in the old (2.2) version?

**Comment by madc** [comment]
Ha, yeah, I'm also always the guy on the Bolt repo who finds the subfolder issues..
I really can't remember, if that ever worked, but it should be an easy fix, I'll have a look the couple of days.

**Comment by madc** [comment]
I noticed, that in [_localeswitcher.twig, L12](https://github.com/AnimalDesign/bolt-translate/blob/master/templates/frontend/_localeswitcher.twig#L12) the path is prepend with a `'/'`. removing it solves the issue for, but it might create new ones, I'm not aware of? Also I don't know, what `newslug` does.

**Comment by SahAssar** [comment]
Well, that newslug is the slug in a different locale, or if there isn't one the slug in the current locale. That part you linked to basically checks if there is a slug in the current locale and if there is outputs a link with the current route and route params (but with the new slug), and if there isn't a slug it links to the homepage (or in your case the wrong folder :D )...

Could you try this and see if it works: https://github.com/SahAssar/bolt-translate/commit/4d1e44c77482691e3faba2aaf4b30088e0fb8eb1 ?

**Comment by madc** [comment]
Yes, is does the job! Good find!
