### ISSUE TITLE
Where can I edit the localeswitcher output?

### ISSUE THREAD

**Issue by Puddingboy** [AnimalDesign/bolt-translate#4]
I would like to add a flagicon to every anchor. I would prefer to do this using a span or i tag, using classes to pick the backgrounds.`<i class="lang"></i>`. Where can I edit this?

**Comment by SahAssar** [comment]
You can supply your own twig file for the localeswitcher by calling it with an argument like so: `{{ localeswitcher('_my_localeswitcher_template.twig')|raw }}`. You probably want to base this on the original twig file which you can see [here](https://github.com/AnimalDesign/bolt-translate/blob/master/assets/views/twig/_localeswitcher.twig).

**Comment by Puddingboy** [comment]
Does that loop permit me to use the slug `( en | fr | nl )` from locales aswell? Else I'll just go with the label instead.

**Comment by SahAssar** [comment]
Yep, it's in `{{ locale.slug }}`

**Comment by madc** [comment]
@Puddingboy There is also [a topic at the bolt forum](https://discuss.bolt.cm/d/50-bolt-translate), if you have any further questions.

**Comment by Puddingboy** [comment]
This solved my question.
