### ISSUE TITLE
[BUG] Repeater fielddtype is missing the translateable icon

### ISSUE THREAD

**Issue by madc** [AnimalDesign/bolt-translate#41]
![screenshot from 2016-07-21 20-09-57](https://cloud.githubusercontent.com/assets/343392/17033559/05220ee6-4f7f-11e6-9ae8-34be9b738e19.png)

**Comment by SahAssar** [comment]
We probably want the icon only to show up on the title for the whole repeater, not each field in each repeated element, right? Cause my first thought was to add it to every translatable field in there :D (which would be all of them).

**Comment by madc** [comment]
It would definitely be redundant on every field of the repeater. Putting it in front of "Content", if we take my example should be enough. Also it should be quickly fix by altering the JS a bit..

**Comment by SahAssar** [comment]
yep, should be easy that way... I immediately started thinking if bolt had js events for when it adds repeaters and so on, which, you are right, would be redundant :)
