### ISSUE TITLE
Set current language as first in locales?

### ISSUE THREAD

**Issue by Puddingboy** [AnimalDesign/bolt-translate#5]
Crosspost, got no reply for days...

What approach would you recommend to display the current language as the first link in the list?
originally I had in mind to use 2 loops, loop1 to get the current selection and loop2 to display the other links. On second thought it seemed like a bad approach. The following seems like a better idea:

```
ul
    li class ='active' > cur lang`
    for( langs in locales){
        if(lang != cur lang){
            li>lang
```

The reason I would want this is because now I can tab through the list and use the active link as the trigger. What would be the way to display the current language label and the current language link so I can pull this off? Or perhaps you would recommend an entirely different approach?

I know you are using `app.request.get('_locale')` in the languageswitcher.twig. Can you get the label in a simular manner?

**Comment by SahAssar** [comment]
Hey,

This solution is a bit crude, but should work:

    <ul class="localeswitcher">
        {% for iso, locale in locales if locale.slug == app.request.get('_locale') %}
            {{_self.localeoutput(iso, locale)}}
        {% endfor %}
        {% for iso, locale in locales if locale.slug != app.request.get('_locale') %}
            {{_self.localeoutput(iso, locale)}}
        {% endfor %}
    </ul>
    {% macro localeoutput(iso, locale) %}
        {% if app.request.get('slug') != '' %}
            {% set newslug = get_slug_from_locale(record, iso) ?: record.slug %}
        {% endif %}
        <li {% if locale.slug == app.request.get('_locale') %}class="active"{% endif %}>
            <a href="{{ url(
                app.request.get('_route'), 
                app.request.get('_route_params')|merge({_locale: locale.slug, slug: newslug })
                )}}">
                {{ locale.label }}
            </a>
    {% endmacro %}

**Comment by Puddingboy** [comment]
So you prefer a 2 loops option? In my own attempt I had excluded the link from the loop and used a js object to match a language label with the abrivation. I was just wondering if there was a better method. My attempt.

```
<a href="#" id='language-button' class='language-button'><i class={{app.request.get('_locale')}}></i></a>
<ul class="language-list" id='language-list'>
	{% for iso, locale in locales %}
		{% if app.request.get('_route') != 'homepage' %}
			{% set newslug = get_slug_from_locale(record, iso) %}
		{% endif %}
		{% if locale.slug != app.request.get('_locale') %}
			<li>
				<a href="{{ url(
				app.request.get('_route'), 
				app.request.get('_route_params')|merge({_locale: locale.slug, slug: newslug ?: record.slug})
				)}}"><i class="{{ locale.slug }}"></i>{{ locale.label }}</a>
			</li>
		{% endif %}
	{% endfor %}
</ul>
```

accompanied with a piece of js:

```
var langs = {
		en : 'English',
		fr : 'Français',
		nl : 'Nederlands'
	};

	var cur_lang = langs[langbutton.getElementsByTagName('i')[0].className];
	langbutton.appendChild(d.createTextNode(cur_lang));
```

I wish there was something I could use to create a proper label without having to create several loops or a js attachment.

**Comment by SahAssar** [comment]
@Puddingboy Sorry it's taken me so long to respond to this. I do think that a double loop in twig is going to be much, much more efficient than doing it in JS clientside. I'm still in the early phases of this extension and if adding a feature like this is going to be helpful to you I can imagine it will be helpful for others too. I'll get on this as soon as I have a spare moment :)

**Comment by Puddingboy** [comment]
Please don't make it a priority if you have other debugging to do and important features to add. This will be a minor convenience for my case.

**Comment by SahAssar** [comment]
@Puddingboy If you have any hints for SEO compatibility that would probably be helpful! I'd be very interested in hearing what needs to be done on that front, could you open a issue with those suggestions since I probably need fix some things there for work soon anyway.

**Comment by SahAssar** [comment]
This will probably be a part of #30 in some way (as in a more configurable localeswitcher), so leaving this here...

**Comment by SahAssar** [comment]
Closing as this is the same as #14, but that one has all the meaty stuff about ARIA roles and so on.
