### ISSUE TITLE
feedback messages not being translated

### ISSUE THREAD

**Issue by Puddingboy** [AnimalDesign/bolt-translate#50]
boltforms does currently have no means to return translated errors

```
feedback:
    success: mail sent
    error: failed to send mail
```

I was wondering if there may be some sort of workaround
 ```{% if form.vars.errors|length %}{% endif %}```
something like that.

or in the future you may wanna go for a locale_succes/locale_error

**Comment by madc** [comment]
This should be doable using [bolt-labels](https://github.com/bolt/labels). Have you tried that?

**Comment by Puddingboy** [comment]
bolt-labels is not really suitable for full sentences. I have my own snippet contenttype I use. Rather I wish errors had an error code so that I could fetch the proper translation to these messages based upon the errorcode.

**Comment by SahAssar** [comment]
I think that labels is what you need to use for this. Translate will only handle content, not static text in configs/templates, that is what we use labels for.

Try changing https://github.com/bolt/boltforms/blob/d868af7f6286938f9554259045fa9e61cb351db1/templates/form/_form_theme.twig#L7 to `{{ l(error.message) }}` and then translating in labels.

**Comment by Puddingboy** [comment]
This sure helps. Do you know if there is some kind of overview going about with a list of possible error messages for form and fields?

**Comment by SahAssar** [comment]
Sorry, no idea... I think you can set what errors to show in boltforms though, using the `message` key on each of the fields, and besides those it should just be the ones that you can set in the boltforms config.

**Comment by Puddingboy** [comment]
Thx anyways, I will root around some more

**Comment by madc** [comment]
Closing this, as it is solved and not directly related with bolt-translate.
