### ISSUE TITLE
[BUG] MySQL Exception: Specified key was too long

### ISSUE THREAD

**Issue by EzeRangel** [AnimalDesign/bolt-translate#56]
Details
-------

 - Translate Version: [ 3.1.0 ]
 - Install type: [ Extension Repository ]
 - Bolt Version: [ 3.0.11 ]
 - PHP version: [ 5.5.38 ]
- MySQL version: [ 5.6.20 MySQL Community Server (GPL) ]
 - Used webserver: [ Apache ]

Reproduction
------------

It seems that when I try to update my DB after the extension installation, MySQL throws and exception related to the INDEX CREATION.

This is the exception - `SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`

Here's an screenshot

![captura de pantalla 2016-08-02 a las 2 50 39 p m](https://cloud.githubusercontent.com/assets/1395261/17345976/e58e8f46-58c5-11e6-8723-074efe4230e6.png)

**Comment by SahAssar** [comment]
@EzeRangel Could you try changing this: https://github.com/AnimalDesign/bolt-translate/blob/master/src/Storage/ContentTypeTable.php#L35 to 255 and see if that helps?

Seems like the MySQL length for a utf8 char is 3 bytes, so 767 / 3 = 255.666666667, so 255 should be okay, and then if it works I can patch that into the next release :)

**Comment by EzeRangel** [comment]
That's it

Everything is right :)
