### ISSUE TITLE
issue of $contentTables[$contentType] = $app->share() in TranslateExtension.php

### ISSUE THREAD

**Issue by cigear** [AnimalDesign/bolt-translate#58]
There is one issue  as below.
 If you define some content types as en-pages or en_pages including character of  _ , - , 
two tables as en-pages and  en_pages will be required  to create and some errors 
will occur.

-------------------------------------------------------------------
private function registerOverrides(Application $app) in TranslateExtension.php

$app['schema.content_tables'] = $app->extend(
    'schema.content_tables',
    function ($contentTables) use ($app) {
        $config = $app['translate.config'];
        $platform = $app['db']->getDatabasePlatform();
       $prefix = $app['schema.prefix'];
       $contentTypes = $app['config']->get('contenttypes');

            foreach (array_keys($contentTypes) as $contentType) {
                $contentTables[$contentType] = $app->share(function () use ($platform, $prefix, $config) {
                    return new Storage\ContentTypeTable($platform, $prefix, $config);
                });
            }
            return $contentTables;
        }
    );
   
----------------------------------------------------------------------------------    
  
  $contentTables[$contentType] should be $contentTables[$tablename];

You could get $tableName as below.
$tableName = $contentTypes[$contentType]['tablename'];

**Comment by SahAssar** [comment]
Fixed in f73153d, thanks!
