### ISSUE TITLE
[BUG?] Unwanted German locale instead of Dutch

### ISSUE THREAD

**Issue by evertalbers** [AnimalDesign/bolt-translate#66]
Details
-------

 - Translate Version: [ 3.1.1 ]
 - Install type: [ Local install ]
 - Bolt Version: [ 3.0.12 ]
 - PHP version: [ ~~7.0~~ 5.6 just had to switch back to 5.6 for reasons not related to this site ]
 - Used webserver: [ Apache ] version [ ? ]
 - For UX/UI issues: [ Chrome ]

Reproduction
------------
I have installed the Translate and Labels Extension and have set the first field in the backend to ```is_translateable: true```

In config.yml I have 
```locales:
  en_GB:
    label: English
    slug: en
  nl_NL:
    label: Nederlands
    slug: nl
```

The translation option shows up, but now lets me choose between English and German, but no Dutch.
![options](https://cloud.githubusercontent.com/assets/3974120/17731236/c6adee52-646c-11e6-8371-ff8732a1ac99.png)
(* _...which is extremely sensitive since the soccer world cup of 1974_ )

I emptied the cache and checked the DB, but saw no effect.

**Comment by SahAssar** [comment]
Wait, in config.yml or in translate.animal.yml? The locales go in the extension config, not in the config.yml.

**Comment by evertalbers** [comment]
That explains a lot. Solved. Thanks!
(I could have known this from my Boltforms experience.)

And so here we have another suggestion to add to the docs. Which files are being installed, what they do etc.

And I presume that the .animal. in the filename has something to do with Github and/or versionmanagement, but it may look a bit confusing to some (with all respect to Animal of course)

![muppets-animal](https://cloud.githubusercontent.com/assets/3974120/17736479/58e9d4be-6488-11e6-8ab0-4ce5af529c85.gif)

**Comment by SahAssar** [comment]
Yeah, clarifying that in the docs sounds good. Basically all extension configs for bolt get their own file called extensionName.authorNamespace.yml, this project has the namespace animal since it was started by AnimalDesign. #54 by @sbonardt still needs a bit of editing (it mentions the need to manually copy the file, which one does not), but will hopefully take care of this :+1:
