### ISSUE TITLE
[RFC] problem with url/routing

### ISSUE THREAD

**Issue by evertalbers** [AnimalDesign/bolt-translate#67]
In the same install as in issue #66 I seem to have a problem with the routing. 

It could be related with the contenttypes where I have (inside a repeated YAML node BTW)
```
        slug:
            type: slug
            uses: title
```

I saved the record after installing the extension, with slightly different text for both languages.
The url for that record used to be 
/project/scira-sheringham-shoal-gb-317-mw
I would now expect it to be 
/en/project/scira-sheringham-shoal-gb-317-mw

but there I get the screen below. 

I suspect that I should have adapted one extra thing somewhere. Should I delete the slug field in the contenttypes?

![php_fatal_error_vendor_library_-_2016-08-17_11 52 42](https://cloud.githubusercontent.com/assets/3974120/17732265/378b5282-6471-11e6-867c-e987c5e8fb12.png)

**Comment by SahAssar** [comment]
Do you still have a contenttype called pages (not that it's required, just to help find the issue)? Cause the issue seems to be that it tries to find a repository called pages but can't find one...

**Comment by evertalbers** [comment]
No, I don't have a 'pages' contenttype in my contenttypes.yml

I have had "pages" just after the install before importing my own contenttypes.yml, and there was still an empty 'pages' table in the MySQL table somewhere, I renamed it to see if that made any difference, but that did not help I think. 

But there's probably still "page/pages" references in other locations that I'm not aware of. The error does not mention 'pages' out of te blue. 

(Currently I do have the Dutch equivalent "paginas" but I'm not using the word "pages" here
```
paginas:
    name: Paginas
    singular_name: Pagina
```
)

Anywhere else that I should look?

**Comment by SahAssar** [comment]
Seems like the error came to in #38 which introduced a hardcoded reference to the pages contenttype. 
This line: https://github.com/AnimalDesign/bolt-translate/blob/master/src/TranslateExtension.php#L246 needs to be changed to something like `$repo = $app['storage']->getRepository($content->contenttype['slug']);`

**Comment by evertalbers** [comment]
Copy-pasted your code, still an error but a different one: 
**Bolt \ Exception \ InvalidRepositoryException
Attempted to load repository for invalid class or alias: . Check that the class, alias or contenttype definition is correct.**

You said _"to be changed to something like..."_ but I'm afraid that I don't have the php skills to come up with other options for that line :-(

**Comment by SahAssar** [comment]
Right, we need to actual content record first to do that... I'm not really at a computer where I can test/fix it right now, but you want to try `$repo = $app['storage']->getRepository($request->get('contenttypeslug'));` that might work. Otherwise I'll take a look at it in the coming days.

**Comment by evertalbers** [comment]
Brilliant, that last one worked. Looks like I can go ahead now, until I meet the next hurdle.

Thanks so far! 
I assume the above change will be in the next Bolt-Translate update?

**Comment by SahAssar** [comment]
@evertalbers Yep, this will get fixed in the next update... I'll just have to test that fix a bit to make sure it doesn't break taxonomy routes.

**Comment by madc** [comment]
I think, this solution will fail on single pages, because then `$request->get('contenttypeslug')` in your example would hold `Pagina`.

**Comment by SahAssar** [comment]
@madc I think bolt aliases the slug and the singular_slug to point to the same repository, but I'll have to test before I can say for sure.

**Comment by madc** [comment]
I did a quick test on the 3.0.12 release with +`pages`/`page` and it gave me some error indicating that `page` is no valid contenttype..

**Comment by evertalbers** [comment]
I'm not sure if it's the answer to your slug question above, but in my "project" contenttype, multilinguality seems to work fine so far: slug, {{ project.link }}, routing all work well.

**Comment by frozenshadow** [comment]
Same problem here. Did multiple clean installs (Bolt 3.0.12), all single page views got 404 errors after installing translate. Also upgraded one install from 2.2.23 to 3.0.12 and got an fatal error (because there wasn't a 404 page in the theme):
```
Request URL: bolt.prod/nl/page/over-ons
Symfony\Component\HttpKernel\Exception\HttpException thrown with message "Page page/ not found."

Stacktrace:
#9 Symfony\Component\HttpKernel\Exception\HttpException in /home/vagrant/projects/bolt-prod/vendor/silex/silex/src/Silex/Application.php:400
#8 Silex\Application:abort in /home/vagrant/projects/bolt-prod/vendor/bolt/bolt/src/Controller/Base.php:62
#7 Bolt\Controller\Base:abort in /home/vagrant/projects/bolt-prod/vendor/bolt/bolt/src/Controller/Frontend.php:155
#6 Bolt\Controller\Frontend:record in /home/vagrant/projects/bolt-prod/extensions/vendor/animal/translate/src/Frontend/LocalizedFrontend.php:78
#5 Bolt\Extension\Animal\Translate\Frontend\LocalizedFrontend:record in /home/vagrant/projects/bolt-prod/vendor/symfony/http-kernel/HttpKernel.php:144
#4 call_user_func_array in /home/vagrant/projects/bolt-prod/vendor/symfony/http-kernel/HttpKernel.php:144
#3 Symfony\Component\HttpKernel\HttpKernel:handleRaw in /home/vagrant/projects/bolt-prod/vendor/symfony/http-kernel/HttpKernel.php:64
#2 Symfony\Component\HttpKernel\HttpKernel:handle in /home/vagrant/projects/bolt-prod/vendor/silex/silex/src/Silex/Application.php:586
#1 Silex\Application:handle in /home/vagrant/projects/bolt-prod/vendor/silex/silex/src/Silex/Application.php:563
#0 Silex\Application:run in /home/vagrant/projects/bolt-prod/public/index.php:14
```

Let me know if you need more info.
