### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Puddingboy** [AnimalDesign/bolt-translate#7]
What do I use to display a translated working searchbar? I've already included the snippet on the frontpage of this repository. The search bar now redirects me to an error page

**Comment by SahAssar** [comment]
Hmm, I haven't tried searching out yet, I'd assume that it will only work for the default language...

**Comment by Puddingboy** [comment]
search should filter on the selected language and only index pages for the current language.

**Comment by SahAssar** [comment]
Yep, agreed. It just might be a bit of a larger solution than I could "hotfix", so I'm putting this on the "todo, but let's get a plan first" pile ;)

**Comment by Puddingboy** [comment]
I am curious about something recently. I have encountered a few situations by now where if I could just get the abrivation of the current language as a global or something simular it would make things a little easier.

For example in the index/header the search action attribute will likely require something like this: `action="{domain}/{lang}/search"`. I am hessitant to literally ask this of you, because I don't know if it is but a symptom of some slightly bigger issue in which case solving the bigger issue takes priority and may even make the need for a {lang} twig tag irrelevant.

**Comment by SahAssar** [comment]
@Puddingboy Any reason {{ app.request.get('_locale') }} does not work for you?

**Comment by Puddingboy** [comment]
In a previous attempt it didn't work. My bad. I suppose I had a syntax error or copied the wrong line. Sorry for the inconvenience.

**Comment by SahAssar** [comment]
@Puddingboy No problem :)
