### ISSUE TITLE
[RFC] Show language slug in the backend

### ISSUE THREAD

**Issue by evertalbers** [AnimalDesign/bolt-translate#71]
The slug (translated as "Permalink" in Dutch example below) field in the backend now combines  contenttype/slug, conveniently showing under which url the record can be found.

![edit_pagina_ _projects_ _profin_cms_-_2016-08-27_08 52 22](https://cloud.githubusercontent.com/assets/3974120/18025771/31985878-6c34-11e6-8f76-838ef230d61f.png)

Is it a good idea to add the language slug in this field? 

And to take things one step further, to  show the url with the routing settings taken into account? In this example of my site, that would be `en/projects`.

It might be best to show these as an extra read-only field, accompanied by some explanation of what it is you're looking at. Actually, the latter would be a suggestion for the Bolt core, and not for Bolt-translate.

**Comment by SahAssar** [comment]
This is one of those things that I want to do, but is sorta dependent on core bolt work, specifically bolt/bolt/issues/4767. Once that gets fixed this should either work automatically or be an easy fix, but lets leave this open so I remember to test it once that lands :)

**Comment by SahAssar** [comment]
Sorta eased by #103 and will be fixed by bolt/bolt#4767. Closing for now, please reopen if it still doesn't work after bolt/bolt#4767 is fixed!
