### ISSUE TITLE
Another routing question

### ISSUE THREAD

**Issue by evertalbers** [AnimalDesign/bolt-translate#76]
I picked up work  on the site that I want to make multilingual again, made some steps on the homepage, but seem to get stuck somewhere in the routing/showing-records department:

I get a 404 on a link to a pagina contenttype record, /en/pagina/risicobeheer-in-duurzame-energie but where it says `Page pagina/ not found.` (where in the case of a 404) I would expect something like `No route found for ...`

Commented away the routing.yml settings that could be affecting this (below), the pagina record exists under that slug and is published, also tried /en/... and /nl/... urls.

It used to work a couple' weeks back, but I'm not sure which changes I made before the error appeared. Pretty sure it is something that I'm doing wrong, but I can't get my head around it.

![bolt_-_fatal_error _-_2016-09-15_12 21 45](https://cloud.githubusercontent.com/assets/3974120/18546720/bdb2fb64-7b3f-11e6-82eb-c31c0b49b1bd.png)

Details
-------

 - Translate Version: [ 0.x | 2.0 | master ]
 - Install type: [ Extension Repository | Local install ]
 - Bolt Version: [ 3.1.2 ]
 - PHP version: [ 5.6 ]
 - Used webserver: [ Apache ]

```
# This file defines user-definable routes for the frontend of your Bolt website.
# Check below for examples, or read the documentation at http://docs.bolt.cm/templates-routes#routing

# Begin Profin-specific routes

sitemapxml:
  path: /sitemap.xml
  defaults: { _controller: 'Bolt\Extension\Bolt\Sitemap\Extension::sitemapXml' }

sitemap:
  path: /sitemap
  defaults: { _controller: 'Bolt\Extension\Bolt\Sitemap\Extension::sitemap' }

# paginabinding:
#     path:           /{slug}
#     defaults:       { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'pagina' }
#     contenttype:    paginas
# homebinding:
#     path:           /{slug}
#     defaults:       { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'home' }
#     contenttype:    homepages

# categorybinding:
#     path:            /{doelgroepen}/{slug}
#     defaults:        { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'paginas', 'doelgroepen': 'zakelijk' }
#     requirements:
#         doelgroepen: [ 'Bolt\Controllers\Routing::getTaxonomyRequirement', ['particulier', 'zakelijk'] ]
#     contenttype:      paginas

# End of Profin-specific routes

# These are the routes defining the default behaviour of Bolt's frontend. Changing these
# might give unexpected results. If possible, only add NEW routes above these.


homepage:
  path:               /
  defaults:           { _controller: 'Bolt\Controllers\Frontend::homepage' }

search:
  path:               /search
  defaults:           { _controller: 'Bolt\Controllers\Frontend::search' }

# (etc etc)
```

**Comment by SahAssar** [comment]
Could you screenshot the routing tab of the profiler for me?

**Comment by evertalbers** [comment]
This is the one from the url **with** the `/en/` or `/nl/`
![symfony_profiler_-_2016-09-17_18 00 53](https://cloud.githubusercontent.com/assets/3974120/18609379/22b788be-7d01-11e6-8e29-dc5a72855a39.png)

I guess you want the first one, but just in case you need it  the one from the url **without** the `/en/` or `/nl/` in the url.
![symfony_profiler_-_2016-09-17_18 03 03](https://cloud.githubusercontent.com/assets/3974120/18609394/5adf9c5e-7d01-11e6-929f-1523a94fa1b0.png)

**Comment by SahAssar** [comment]
Fixed by updating to dev-master. same issue as #74.
