### ISSUE TITLE
Custom routing results in no auto-redirect to /de or /en

### ISSUE THREAD

**Issue by lswest** [AnimalDesign/bolt-translate#77]
I'm using custom routes in order to translate a variety of contenttypes, but would like my homepage to still redirect according to the language headers.  However, this doesn't seem to be possible once disabling the routing_overrides in the config file.

Details
-------

 - Translate Version: [ dev-master ]
 - Install type: [ Extension Repository ]
 - Bolt Version: [ 3.1.2 ]
 - PHP version: [ 7.0 ]
 - Used webserver: [ Apache  ] version [ 2.4.10 ]

Reproduction
------------

Disable routing overrides, and then try to load the root page of your site - it will cause an error page, instead of redirecting to /en or /de.

Problem Origin
--------------

There are lines in the file vendor/animal/translate/src/Frontend/LocalizedFrontend.php (lines 33-38) that read:
```
            $routes = array_merge([
                    'homepageredir' => [
                        'path' => '/',
                        'defaults' => ['_controller' => 'controller.frontend:homepageRedirect']
                    ]
                ], $routes);
```
This seems to add an entry to the routing.yml file in order to link the root path to the homepageRedirect function (in the same file), which handles the actual redirect.  By disabling routing_override, the controller entry is no longer created.

Solution
------------

To solve this, you must simply create the entry manually.  I originally tried it using the namespace of the extension, which didn't work, but copying the controller line directly from the PHP script did indeed work.

The lines I added to routing.yml are:
```
homepageredir:
    path:               /
    defaults:           { _controller: 'controller.frontend:homepageRedirect'}
```

**Comment by lswest** [comment]
@SahAssar It didn't work quite "out of the box", but I found a solution while actually writing this issue.  Therefore, I'm closing it straight off the bat, but for anyone who needs the information, it's there.

**Comment by SahAssar** [comment]
@lswest This is one of those things where we need better (or any) docs... Glad you found a solution, but I'm going to reopen this and tag it to make sure that we get docs for it if you don't mind :)

**Comment by lswest** [comment]
If you want, I can write up the docs for this particular scenario. I'd just need to know your preferred approach.

**Comment by SahAssar** [comment]
@lswest I was planning to create a repo/site with basically a clone of the docs repo but with just info on translate. If you want to write up a `.md` file and PR it into a `docs` folder on this repo that'd greatly appreciated. Then we can have that as a start of our docs and then move it into proper docs :)
