### ISSUE TITLE
Using 'where' in translateable items

### ISSUE THREAD

**Issue by evertalbers** [AnimalDesign/bolt-translate#83]
Is it possible that using 'where' as in https://docs.bolt.cm/3.1/templating/content-fetching#using-code-where-code does not work for translatable fields? 
I tried it in a boolean (to filter out consciously-untranslated items in a list) and that did not work.

Now using an if-then loop, but 'where' would be better to get a proper pagination.

**Comment by SahAssar** [comment]
`where` works on the default contenttype, not on translated values. This is because the values arent replaced with translated ones until after the records are fetched from db and are being hydrated.

**Comment by evertalbers** [comment]
OK, thanks.
