### ISSUE TITLE
og:locale in Bolt SEO Premium Extension™ v0.10.3 Platinum Edition Pro

### ISSUE THREAD

**Issue by evertalbers** [AnimalDesign/bolt-translate#84]
- Translate Version: [ dev-master (cc99e0) ]
- Install type: [ Extension Repository  ]
-  Bolt SEO Premium Extension™ v0.10.3 Platinum Edition Pro Version: v0.10.3
- Bolt Version: [ 3.1.4 ]

I see that the default install of aforementioned plugin does not 'pick up' the locale, on a Dutch example it still says
`<meta property="og:locale" content="en_GB" />`

**Comment by SahAssar** [comment]
This is because the SEO extension gets the locale from the config file instead of the set locale, could you try replacing https://github.com/bobdenotter/seo/blob/master/templates/_metatags.twig#L7 with `<meta property="og:locale" content="{{ htmllang()|replace({'-': '_'}) }}" />`?

**Comment by evertalbers** [comment]
Yep, it worked! Maybe you will want to add this to the translate docs somewhere? 

Related, I also made a pull request for Bolt SEO Premium Extension™ https://github.com/bobdenotter/seo/pull/31

**Comment by SahAssar** [comment]
Hmm, I was hoping to get a more permanent (and automatic) fix in, @bobdenotter would you be okay with that?

**Comment by bobdenotter** [comment]
@SahAssar Yes, sounds good. If you have a plan, I'm all for that. :-)

**Comment by evertalbers** [comment]
In that case you could also look at pre-filling title/meta fields from Translate-pages to SEO.

**Comment by SahAssar** [comment]
PR opened in the seo repo.

**Comment by madc** [comment]
The two PRs have been merged. Does that mean, we can close this issue? @SahAssar was mentioning, its only a temporary fix..

**Comment by SahAssar** [comment]
It's good enough for me :)
