### ISSUE TITLE
What is happening to my page url and how do I fix it

### ISSUE THREAD

**Issue by Puddingboy** [AnimalDesign/bolt-translate#9]
```
{domain}/{lang}/slug-ohx8xv
{domain}/{lang}/slug-dkg9yl
{domain}/{lang}/slug-5s0r1v
```
These are what my page urls look like.
How do I fix the slug?

**Comment by SahAssar** [comment]
If you have tagged the slug field as translatable it will try to generate a slug for that language. You probably need to go into those records and click the unlock button to re-generate those slugs to make them "pretty".
