### ISSUE TITLE
[BUG] _sub_menu_translated.twig is not defined

### ISSUE THREAD

**Issue by zomars** [AnimalDesign/bolt-translate#93]
Details
-------

 - Translate Version: 4.0.1
 - Install type: Local install
 - Bolt Version: 3.2.5
 - PHP version: 7.0
 - Used webserver: Apache version 2.4

Reproduction
------------

When trying to use `{{ menu(template = '@bolt/frontend/_sub_menu_translated.twig') }}` from the docs I get and undefined twig error, also I can't seem to find the file anywhere.

![captura de pantalla 2017-01-03 a la s 17 31 03](https://cloud.githubusercontent.com/assets/3504472/21628220/fabc603a-d1da-11e6-8515-debc5f70c24d.png)

**Comment by SahAssar** [comment]
Is the file actually there (in the frontend folder)? I haven't tagged a release with that file in it yet since I was hoping to fix some of the other bugs too, so it might just be that you are looking at the docs for the master branch, but have 4.0.1 installed.

**Comment by zomars** [comment]
I guess you're right. The file is not present.

**Comment by SahAssar** [comment]
Alright, closing for now, please reopen if it still occurs when a new version is tagged (hopefully this weekend)
