### ISSUE TITLE
[BUG] Admin error when routes are not defined

### ISSUE THREAD

**Issue by benwallis** [AnimalDesign/bolt-translate#98]
Twig_Error_Runtime in Template.php line 453: 
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "preview" as such route does not exist.") in "@bolt/fields/_locale.twig" at line 62.

Details
-------

 - Translate Version:  4.0.1
 - Install type: Extension Repository
 - Bolt Version: 3.2.4
 - PHP version: 5.6
 - Used webserver: Apache 2

Reproduction
------------

I have a very simple single-page website so I had commented out most of the routes in /app/config/routing.yml but this causes the above error when trying to edit translatable content in Bolt admin.

The error is caused by lines 62 and 70 in /extensions/vendor/animal/translate/templates/fields/_locale.twig.

To reproduce just comment out the "preview" route in /app/config/routing.yml
Log into Bolt admin and try to edit a contenttype or template ithat has been defined as translatable.

I think this could be fixed by checking for the route first, as done in Bolt core:
/vendor/bolt/bolt/app/view/twig/editcontent/_aside-preview.twig
`{% if app.routes.get('preview') %}`

Would also need to do a similar check for the "contentlink" route:
`{% if app.routes.get('contentlink') %}`

**Comment by SahAssar** [comment]
Sorry, but I'm going to close this. Bolt in a number of places assume that the default routing is there, and we in the Bolt team plan to change this in the future (when re-hauling the backend to make it more configurable), but for now those routes are "required". Please see bolt/bolt/issues/6165 for more context.
